###  Create numpy arrays

### we can store only 1 type of datatype in numpy whether it is int, float or string. if we change any of the value the whole is changed to that data type

In [4]:
import numpy as np

In [18]:
nums=[[1,2,3],[4,5,6]]
nums=np.array(nums)
nums

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
nums.ndim #dimension

2

In [20]:
nums.shape #rows and columns.....

(2, 3)

In [21]:
nums.dtype

dtype('int32')

###  creating numpy using functions

## zeros 

In [30]:
arr=np.zeros(5)
arr
arr1=np.zeros((2,3))
arr1

array([[0., 0., 0.],
       [0., 0., 0.]])

## ones

In [31]:
arr=np.ones(4)
arr

array([1., 1., 1., 1.])

In [32]:
arr=np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

### using eye function we get a 2d identity matrix of given order... syntax eye(N(rows),M(columns),k=0(can be 1, 2,,,, position of diagonal value, dtype(datatype)) 

In [33]:
arr=np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
arr=np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# diag 

### in diag function it will take an input of diagonal enteries and it wil give us mxn matrix 

In [38]:
arr=np.diag([4,5.8,9,10])
arr

array([[ 4. ,  0. ,  0. ,  0. ],
       [ 0. ,  5.8,  0. ,  0. ],
       [ 0. ,  0. ,  9. ,  0. ],
       [ 0. ,  0. ,  0. , 10. ]])

In [39]:
np.diag(arr)

array([ 4. ,  5.8,  9. , 10. ])

### generating random number 

In [41]:
rand_arr=np.random.randint(2,10,5) # these random numbers may include lower limit i.e.2 but it does not include upperlimt i.e. 10
rand_arr

array([8, 9, 5, 7, 7])

In [51]:
# in randint function we pass 3 parameters but in rand function we pass only 1 parameter
# "rand " will gives us numbers taht follows uniform distribution
arr=np.random.rand(4) # here it will give us 4(n)  floating pint numbers between 0 and 1
arr

array([0.8567607 , 0.82037592, 0.65533907, 0.44986841])

In [44]:
# if we want to find 2-d array we will write its code as
arr=np.random.rand(2,3)
arr

array([[0.157687  , 0.70174039, 0.86639991],
       [0.37663994, 0.72689092, 0.58580226]])

In [50]:
# in the function "randn" we get n numbers centred at 0 following standard normal distribution
arr=np.random.randn(50)
print(arr)
np.mean(arr)

-0.02376131096946036